services:
  obds-fhir-to-opal:
    image: ghcr.io/bzkf/onco-analytics-on-fhir/obds-fhir-to-opal:master@sha256:40d5316f6fc484edf8c0a634d398cee779e8a531324fe71e9879c84d4722d119
    restart: no
    cap_drop:
      - ALL
    privileged: false
    ipc: private
    security_opt:
      - "no-new-privileges:true"
    user: "1001:1001"
    environment:
      OUTPUT_FOLDER: "/home/spark/opal-output"
      KAFKA_BOOTSTRAP_SERVER: "kafka:9092"
      KAFKA_PATIENT_TOPIC: "fhir.obds.Patient"
      KAFKA_CONDITION_TOPIC: "fhir.obds.Condition"
      KAFKA_OBSERVATION_TOPIC: "fhir.obds.Observation"
      KAFKA_PROCEDURE_TOPIC: "fhir.obds.Procedure"
      KAFKA_MEDICATIONSTATEMENT_TOPIC: "fhir.obds.MedicationStatement"
      KAFKA_TOPIC_YEAR_SUFFIX: ""
    volumes:
      - ${PWD}/csv-output:/home/spark/opal-output
